DROP TABLE IF EXISTS COUNTRY CASCADE;
DROP TABLE IF EXISTS STATE CASCADE;
DROP TABLE IF EXISTS CITY CASCADE;
DROP TABLE IF EXISTS ADMIN CASCADE;
DROP TABLE IF EXISTS ROLE CASCADE;
DROP TABLE IF EXISTS USERS_AUTHORITIES CASCADE;
DROP TABLE IF EXISTS Property_Category CASCADE;

CREATE TABLE COUNTRY
(
 id INT generated by default as identity,
 country VARCHAR(500) NOT NULL,
 country_code VARCHAR(10) NOT NULL,
 phone_code VARCHAR(200) NOT NULL,
 PRIMARY KEY(id)
);

CREATE TABLE STATE(
id INT,
state VARCHAR(500) NOT NULL,
country_id int NOT NULL,
CONSTRAINT fk_state FOREIGN KEY (country_id) REFERENCES COUNTRY(id),
PRIMARY KEY(id)
);

CREATE TABLE CITY(
id INT,
city VARCHAR(500),
state_id INT,
CONSTRAINT fk_city FOREIGN KEY (state_id) REFERENCES STATE(id),
PRIMARY KEY(id)
);

CREATE TABLE ADMIN(
id INT,
first_name VARCHAR(500) NOT NULL,
last_name VARCHAR(500) NOT NULL,
active boolean NOT NULL,
failed_attempt INT NOT NULL,
date_non_block TIMESTAMP,
is_block boolean NOT NULL,
max_attempt INT NOT NULL,
email VARCHAR(500) NOT NULL,
mobile VARCHAR(500) NOT NULL,
password VARCHAR(40) NOT NULL,
user_type VARCHAR(50) NOT NULL,
created_at timestamp,
updated_at timestamp,
role int8 ,
PRIMARY KEY(id)
);

CREATE TABLE ROLE(
id INT,
active boolean NOT NULL,
description VARCHAR(500) NOT NULL,
slug_name VARCHAR(200) NOT NULL UNIQUE,
name VARCHAR(200) NOT NULL,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP,
created_by INT NOT NULL,
authorities INT,
CONSTRAINT FKe6hmka5t4wedfb77k1afcnodw FOREIGN KEY (created_by) REFERENCES ADMIN(id),
PRIMARY KEY(id)
);

CREATE TABLE USERS_AUTHORITIES(
id INT,
active boolean NOT NULL,
description VARCHAR(500) NOT NULL,
access_rights VARCHAR(500) NOT NULL,
created_at TIMESTAMP NOT NULL,
updated_at timestamp,
created_by INT NOT NULL,
role int8,
CONSTRAINT FK3h58lf3gyj9mel2affdpqut0x FOREIGN KEY (role) REFERENCES ROLE(id),
CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES ADMIN(id),
PRIMARY KEY (id)
);

CREATE TABLE Property_Category(
id Integer GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(500) NOT NULL,
description VARCHAR(500) NOT NULL,
slug_name VARCHAR(500) NOT NULL,
user_type VARCHAR(500) NOT NULL,
created_at TIMESTAMP NOT NULL,
updated_at timestamp,
admin_id int8,
CONSTRAINT fk_created_by FOREIGN KEY (admin_id) REFERENCES ADMIN(id),
PRIMARY KEY(ID)
);

alter table if exists admin
      add CONSTRAINT FK6knun6449hpmgsljqty9xbmhy FOREIGN KEY (role) REFERENCES ROLE(id);

INSERT INTO ADMIN(id,first_name,last_name,active,failed_attempt,is_block,max_attempt,email,password,user_type,created_at,updated_at,mobile) VALUES(1,'Ankit','Srivastava','true',3,false,3,'ankitsrivastava7835@gmail.com','kDdARQrIGaM=','SYSTEM_ADMIN','2021-01-04',null,'9990545169');

INSERT INTO ROLE(id,active,slug_name,name,description,created_at,updated_at,created_by) VALUES(1,true,'SYSTEM_ADMIN','Admin','SYSTEM_ADMIN','2022-01-04',null,1);
INSERT INTO ROLE(id,active,slug_name,name,description,created_at,updated_at,created_by) VALUES(2,true,'OWNER','Owner','OWNER','2022-01-04',null,1);
INSERT INTO ROLE(id,active,slug_name,name,description,created_at,updated_at,created_by) VALUES(3,true,'Agent','Agent','Agent','2022-01-04',null,1);
INSERT INTO ROLE(id,active,slug_name,name,description,created_at,updated_at,created_by) VALUES(4,true,'Builder','Builder','Builder','2022-01-04',null,1);

INSERT INTO USERS_AUTHORITIES(id,active,description,access_rights,created_at,updated_at,created_by) VALUES(1,true,'Admin access all resources','/api/v1/admin','2022-01-04',null,1);
INSERT INTO USERS_AUTHORITIES(id,active,description,access_rights,created_at,updated_at,created_by,role) VALUES(2,true,'Property owner can access limited resources','/api/v1/property','2022-01-04',null,1,1);
INSERT INTO USERS_AUTHORITIES(id,active,description,access_rights,created_at,updated_at,created_by,role) VALUES(3,true,'Property Agent can access limited resources','/api/v1/property','2022-01-04',null,1,1);
INSERT INTO USERS_AUTHORITIES(id,active,description,access_rights,created_at,updated_at,created_by,role) VALUES(4,true,'Property Builder can access limited resources','/api/v1/property','2022-01-04',null,1,1);

update ADMIN SET role=1 where id=1;
update role set authorities=1 where id=1;
update role set authorities=2 where id=2;
update role set authorities=3 where id=3;
update role set authorities=4 where id=4;

update USERS_AUTHORITIES set role=1 where id=1;
update USERS_AUTHORITIES set role=2 where id=2;
update USERS_AUTHORITIES set role=3 where id=3;
update USERS_AUTHORITIES set role=4 where id=4;

INSERT INTO COUNTRY(id,country,country_code,phone_code) VALUES(1,'India','IND','+91');
INSERT INTO STATE(id,state,country_id) VALUES(1,'Delhi',1);
INSERT INTO STATE(id,state,country_id) VALUES(2,'Uttar Pradesh',1);
INSERT INTO CITY(id,city,state_id) VALUES(1,'New Delhi',1);
INSERT INTO CITY(id,city,state_id) VALUES(2,'Noida Sector 62',2);

INSERT INTO property_category(name,description,slug_name,user_type,admin_id,created_at,updated_at) VALUES('Apartment','Apartment','Apartment','SYSTEM_ADMIN',1,'2022-01-17',null);
